name: Go Unit Test and Coverage

on:
  push:
    branches:
      - main  # 替换为你的默认分支名
  pull_request:
    branches:
      - main  # 替换为你的默认分支名

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18  # 根据你的需要设置 Go 的版本

      - name: Download dependencies and run tests
        run: |
          cd Kamakura/devhub/project_code/project_goland/
          go mod download
          go test -coverprofile=coverage.out ./...

      - name: Generate and upload coverage report
        run: |
          cd Kamakura/devhub/project_code/project_goland/
          go tool cover -html=coverage.out -o coverage.html
          echo "Coverage report generated"

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: Kamakura/devhub/project_code/project_goland/coverage.html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
